("debian"             "taffish-org/debian")
("python"             "taffish-org/python")
("sbcl"               "taffish-org/sbcl")
("R"                  "taffish-org/R")

("muscle"             "taffish-org/muscle")
("MCScanX"            "taffish-org/MCScanX")
("uniprot-idmapping"  "taffish-org/uniprot-idmapping")
("juicer"             "taffish-org/juicer")

("blast"              "taffish-org/blast")
("cdhit"              "taffish-org/cdhit")
("hmmer"              "taffish-org/hmmer")
("get-seqs-from-ids"  "taffish-org/get-seqs-from-ids")
("gene-family-search" "taffish-org/gene-family-search")

("sra-tools"          "taffish-org/sra-tools")
("seqtk"              "taffish-org/seqtk")
("fastqc"             "taffish-org/fastqc")
("trim_galore"        "taffish-org/trim_galore")
("STAR"               "taffish-org/STAR")
("subread"            "taffish-org/subread")
