;;BASE
("debian"             "taffish-org/debian")
("python"             "taffish-org/python")
("conda"              "taffish-org/conda")
("sbcl"               "taffish-org/sbcl")
("R"                  "taffish-org/R")
("intel-oneapi"       "taffish-org/intel-oneapi")
("hello"              "taffish-org/hello")

;;TOOLs
("muscle"             "taffish-org/muscle")
("MCScanX"            "taffish-org/MCScanX")
("uniprot-idmapping"  "taffish-org/uniprot-idmapping")
("juicer"             "taffish-org/juicer")

;;;gene-family-search
("blast"              "taffish-org/blast")
("cdhit"              "taffish-org/cdhit")
("hmmer"              "taffish-org/hmmer")
("get-seqs-from-ids"  "taffish-org/get-seqs-from-ids")
("gene-family-search" "taffish-org/gene-family-search")

;;;RNA-seq
("sra-tools"          "taffish-org/sra-tools")
("seqtk"              "taffish-org/seqtk")
("fastqc"             "taffish-org/fastqc")
("trim_galore"        "taffish-org/trim_galore")
("STAR"               "taffish-org/STAR")
("subread"            "taffish-org/subread")

;;;T2T
("bedtools"           "taffish-org/bedtools")
("samtools"           "taffish-org/samtools")
("bcftools"           "taffish-org/bcftools")
("bowtie2"            "taffish-org/bowtie2")
("fastp"              "taffish-org/fastp")

;;others
("kallisto"           "taffish-org/kallisto")
("bustools"           "taffish-org/bustools")
("hisat2"             "taffish-org/hisat2")
("mafft"              "taffish-org/mafft")
("clustal-omega"      "taffish-org/clustal-omega")
("bwa"                "taffish-org/bwa")
("gatk"               "taffish-org/gatk")
("salmon"             "taffish-org/salmon")
("Trinity"            "taffish-org/Trinity")
("freebayes"          "taffish-org/freebayes")
("pymol"              "taffish-org/pymol")
("hifiasm"            "taffish-org/hifiasm")
("haphic"             "taffish-org/haphic")
("autodock-vina"      "taffish-org/autodock-vina")
("rosetta"            "taffish-org/rosetta")
("gromacs"            "taffish-org/gromacs")
("MMseqs2"            "taffish-org/MMseqs2")
("foldseek"           "taffish-org/foldseek")
("esm-fold"           "taffish-org/esm-fold")
("jellyfish"          "taffish-org/jellyfish")
("genomescope"        "taffish-org/genomescope")
("kmc"                "taffish-org/kmc")
